# fly.toml
app = "ai-job-processor"
primary_region = "arn" # fly platform regions

[build]
  dockerfile = "Dockerfile"

[deploy]
  # "rolling" дешевше і стабільніше для мікро-машин, ніж "bluegreen"
  strategy = "rolling"

# ===============================================
# 🚀 0. Processes
# ===============================================

[processes]
  web = "node dist/src/server.js"
  worker = "node dist/src/worker/index.js"
  # Important: використовуємо повний шлях до бінарника, який є в офіційному образі Redis
  # redis = "redis-server --dir /data/redis --save 60 1 --appendonly no"

# ===============================================
# 🚀 1. Volumes
# ===============================================
# [[mounts]]
  # fly volumes create redis_data --region arn --size 1
  # source = "redis_data"   # Name which we give to the volume on creation
  # destination = "/data/redis" # Path inside the container
  # processes = ["redis"]      # IMPORTANT: disk is attached ONLY to the redis process

# ===============================================
# 🚀 2. VM Resources
# ===============================================
[[vm]]
  processes = ["web"]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm]]
  processes = ["worker"]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# [[vm]]
#   processes = ["redis"]
#   image = "redis:7-alpine" # Because we don't have redis in our main Dockerfile
#   cpu_kind = "shared"
#   cpus = 1
#   memory_mb = 256

# -----------------------------------------------
# WEB (API Server) -
# -----------------------------------------------
[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static"

[[services]]
  processes = ["web"]
  internal_port = 4000
  # AUTO_STOP: if no traffic = $0 for that time
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.http_checks]]
    interval = "20s"      # Slightly increased interval to give the DB breathing room
    timeout = "8s"        # Greater than REQUEST_TIMEOUT (see db connectionTimeoutMillis)
    grace_period = "20s"  # Nano instances need warm-up time
    method = "GET"
    path = "/health"
    protocol = "http"
    restart_limit = 3

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# -----------------------------------------------
# REDIS (Internal only)
# -----------------------------------------------

# [[services]]
#   processes = ["redis"]
#   internal_port = 6379
#   protocol = "tcp"

#   min_machines_running = 1

#   [[services.tcp_checks]]
#     interval = "20s"
#     timeout = "2s"
