# fly.toml
app = "ai-job-processor"
primary_region = "iad" # Chose closest region

[build]
  dockerfile = "Dockerfile"

# ===============================================
# 🚀 1. API (Web Process)
# ===============================================

[processes]
  web = "node dist/server.js"
  worker = "node dist/src/worker/index.js"

# -----------------------------------------------
# WEB (API Server) -
# -----------------------------------------------
[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static"

[[services]]
  processes = ["web"]
  internal_port = 4000

  [[services.http_checks]]
    interval = "20s"      # Slightly increased interval to give the DB breathing room
    timeout = "8s"        # Greater than REQUEST_TIMEOUT (see db connectionTimeoutMillis)
    grace_period = "20s"  # Nano instances need warm-up time
    method = "GET"
    path = "/health"
    protocol = "http"
    restart_limit = 3

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
